// Code generated by mockery 2.9.4. DO NOT EDIT.

package iservices

import mock "github.com/stretchr/testify/mock"

// MockCounterService is an autogenerated mock type for the CounterService type
type MockCounterService struct {
	mock.Mock
}

// Inc provides a mock function with given fields:
func (_m *MockCounterService) Inc() (int64, error) {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
