// Code generated by mockery 2.9.4. DO NOT EDIT.

package irepositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	repositories "github.com/theoptz/url-shortener/internal/repositories"
)

// MockCounterRepository is an autogenerated mock type for the CounterRepository type
type MockCounterRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *MockCounterRepository) Get(_a0 context.Context, _a1 *repositories.RangeItem) (int64, error) {
	ret := _m.Called(_a0, _a1)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *repositories.RangeItem) int64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *repositories.RangeItem) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
