// Code generated by mockery 2.9.4. DO NOT EDIT.

package irepositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	repositories "github.com/theoptz/url-shortener/internal/repositories"
)

// MockLinksRepository is an autogenerated mock type for the LinksRepository type
type MockLinksRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *MockLinksRepository) Create(_a0 context.Context, _a1 repositories.LinkItem) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repositories.LinkItem) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: _a0, _a1
func (_m *MockLinksRepository) GetByID(_a0 context.Context, _a1 int64) (string, error) {
	ret := _m.Called(_a0, _a1)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, int64) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
