// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetLinksCodeHandlerFunc turns a function with the right signature into a get links code handler
type GetLinksCodeHandlerFunc func(GetLinksCodeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLinksCodeHandlerFunc) Handle(params GetLinksCodeParams) middleware.Responder {
	return fn(params)
}

// GetLinksCodeHandler interface for that can handle valid get links code params
type GetLinksCodeHandler interface {
	Handle(GetLinksCodeParams) middleware.Responder
}

// NewGetLinksCode creates a new http.Handler for the get links code operation
func NewGetLinksCode(ctx *middleware.Context, handler GetLinksCodeHandler) *GetLinksCode {
	return &GetLinksCode{Context: ctx, Handler: handler}
}

/* GetLinksCode swagger:route GET /links/{code} getLinksCode

return full link by code

*/
type GetLinksCode struct {
	Context *middleware.Context
	Handler GetLinksCodeHandler
}

func (o *GetLinksCode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetLinksCodeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
