// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/theoptz/url-shortener/internal/server/models"
)

// GetLinksCodeOKCode is the HTTP code returned for type GetLinksCodeOK
const GetLinksCodeOKCode int = 200

/*GetLinksCodeOK link object

swagger:response getLinksCodeOK
*/
type GetLinksCodeOK struct {

	/*
	  In: Body
	*/
	Payload *models.Link `json:"body,omitempty"`
}

// NewGetLinksCodeOK creates GetLinksCodeOK with default headers values
func NewGetLinksCodeOK() *GetLinksCodeOK {

	return &GetLinksCodeOK{}
}

// WithPayload adds the payload to the get links code o k response
func (o *GetLinksCodeOK) WithPayload(payload *models.Link) *GetLinksCodeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get links code o k response
func (o *GetLinksCodeOK) SetPayload(payload *models.Link) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLinksCodeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetLinksCodeNotFoundCode is the HTTP code returned for type GetLinksCodeNotFound
const GetLinksCodeNotFoundCode int = 404

/*GetLinksCodeNotFound A link with specified code was not found

swagger:response getLinksCodeNotFound
*/
type GetLinksCodeNotFound struct {
}

// NewGetLinksCodeNotFound creates GetLinksCodeNotFound with default headers values
func NewGetLinksCodeNotFound() *GetLinksCodeNotFound {

	return &GetLinksCodeNotFound{}
}

// WriteResponse to the client
func (o *GetLinksCodeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetLinksCodeInternalServerErrorCode is the HTTP code returned for type GetLinksCodeInternalServerError
const GetLinksCodeInternalServerErrorCode int = 500

/*GetLinksCodeInternalServerError Internal server error

swagger:response getLinksCodeInternalServerError
*/
type GetLinksCodeInternalServerError struct {
}

// NewGetLinksCodeInternalServerError creates GetLinksCodeInternalServerError with default headers values
func NewGetLinksCodeInternalServerError() *GetLinksCodeInternalServerError {

	return &GetLinksCodeInternalServerError{}
}

// WriteResponse to the client
func (o *GetLinksCodeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
