// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/theoptz/url-shortener/internal/server/models"
)

// PostLinksOKCode is the HTTP code returned for type PostLinksOK
const PostLinksOKCode int = 200

/*PostLinksOK The code for specified link

swagger:response postLinksOK
*/
type PostLinksOK struct {

	/*
	  In: Body
	*/
	Payload *models.Code `json:"body,omitempty"`
}

// NewPostLinksOK creates PostLinksOK with default headers values
func NewPostLinksOK() *PostLinksOK {

	return &PostLinksOK{}
}

// WithPayload adds the payload to the post links o k response
func (o *PostLinksOK) WithPayload(payload *models.Code) *PostLinksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post links o k response
func (o *PostLinksOK) SetPayload(payload *models.Code) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostLinksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostLinksBadRequestCode is the HTTP code returned for type PostLinksBadRequest
const PostLinksBadRequestCode int = 400

/*PostLinksBadRequest The specified link is not an URL

swagger:response postLinksBadRequest
*/
type PostLinksBadRequest struct {
}

// NewPostLinksBadRequest creates PostLinksBadRequest with default headers values
func NewPostLinksBadRequest() *PostLinksBadRequest {

	return &PostLinksBadRequest{}
}

// WriteResponse to the client
func (o *PostLinksBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostLinksInternalServerErrorCode is the HTTP code returned for type PostLinksInternalServerError
const PostLinksInternalServerErrorCode int = 500

/*PostLinksInternalServerError Internal server error

swagger:response postLinksInternalServerError
*/
type PostLinksInternalServerError struct {
}

// NewPostLinksInternalServerError creates PostLinksInternalServerError with default headers values
func NewPostLinksInternalServerError() *PostLinksInternalServerError {

	return &PostLinksInternalServerError{}
}

// WriteResponse to the client
func (o *PostLinksInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
