// Code generated by go-swagger; DO NOT EDIT.

// Package restapi URL Shortener
//
//  Distributed URL Shortener
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /
//  Version: 0.1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
