// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Distributed URL Shortener",
    "title": "URL Shortener",
    "version": "0.1.0"
  },
  "host": "localhost:8080",
  "paths": {
    "/links": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "creates a short link for specified link",
        "parameters": [
          {
            "description": "The link to process",
            "name": "link",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Link",
              "example": {
                "url": "https://example.com"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The code for specified link",
            "schema": {
              "$ref": "#/definitions/Code",
              "example": {
                "application/json": {
                  "code": "Avc2K"
                }
              }
            }
          },
          "400": {
            "description": "The specified link is not an URL"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/links/{code}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "return full link by code",
        "parameters": [
          {
            "minLength": 5,
            "type": "string",
            "description": "short code",
            "name": "code",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "link object",
            "schema": {
              "$ref": "#/definitions/Link",
              "example": {
                "application/json": {
                  "url": "https://example.com/"
                }
              }
            }
          },
          "404": {
            "description": "A link with specified code was not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  },
  "definitions": {
    "Code": {
      "required": [
        "code"
      ],
      "properties": {
        "code": {
          "type": "string",
          "minLength": 5
        }
      }
    },
    "Link": {
      "required": [
        "url"
      ],
      "properties": {
        "url": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Distributed URL Shortener",
    "title": "URL Shortener",
    "version": "0.1.0"
  },
  "host": "localhost:8080",
  "paths": {
    "/links": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "creates a short link for specified link",
        "parameters": [
          {
            "description": "The link to process",
            "name": "link",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Link",
              "example": {
                "url": "https://example.com"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The code for specified link",
            "schema": {
              "$ref": "#/definitions/Code",
              "example": {
                "application/json": {
                  "code": "Avc2K"
                }
              }
            }
          },
          "400": {
            "description": "The specified link is not an URL"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/links/{code}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "return full link by code",
        "parameters": [
          {
            "minLength": 5,
            "type": "string",
            "description": "short code",
            "name": "code",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "link object",
            "schema": {
              "$ref": "#/definitions/Link",
              "example": {
                "application/json": {
                  "url": "https://example.com/"
                }
              }
            }
          },
          "404": {
            "description": "A link with specified code was not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  },
  "definitions": {
    "Code": {
      "required": [
        "code"
      ],
      "properties": {
        "code": {
          "type": "string",
          "minLength": 5
        }
      }
    },
    "Link": {
      "required": [
        "url"
      ],
      "properties": {
        "url": {
          "type": "string"
        }
      }
    }
  }
}`))
}
